/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RegExpForm.java
 *
 * Created on 06-02-2014, 08:19:41 PM
 */
package BuenRecord.RegExp.GUI;

import BuenRecord.Logic.AFGenerator;
import BuenRecord.Logic.AFProcessing;
import BuenRecord.RegExp.Parser.Parser;
import BuenRecord.RegExp.Parser.ParserException;
import BuenRecord.RegExp.Parser.RegularExpresionNode;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.xml.bind.JAXBException;

/**
 *
 * @author Franklin
 */
public class RegExpForm extends javax.swing.JFrame {

    AFGenerator currentTree;
    AFProcessing manager;
    /** Creates new form RegExpForm */
    public RegExpForm() {
        initComponents();
        currentTree = new AFGenerator();
        manager = new AFProcessing();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtRegularExpression = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtChain = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnLoadRegExp = new javax.swing.JButton();
        btnEvaluate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel2.setText("Regular Expressions Evaluator");

        jLabel1.setText("Regular Expression:");

        jLabel3.setText("Chain:");

        btnLoadRegExp.setText("Load");
        btnLoadRegExp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadRegExpActionPerformed(evt);
            }
        });

        btnEvaluate.setText("Evaluate");
        btnEvaluate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEvaluateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(125, 125, 125))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(txtRegularExpression, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                    .addComponent(txtChain, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(btnLoadRegExp, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEvaluate, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRegularExpression, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtChain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLoadRegExp, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEvaluate, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-479)/2, (screenSize.height-292)/2, 479, 292);
    }// </editor-fold>//GEN-END:initComponents

private void btnLoadRegExpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadRegExpActionPerformed
    String regExp = this.txtRegularExpression.getText();
    if(regExp.isEmpty()){
        JOptionPane.showMessageDialog(this,"Regular Expression field can't be empty.", "Invalid Regular Expression", JOptionPane.WARNING_MESSAGE);
        this.txtRegularExpression.requestFocus();
        return;
    }
    Parser parser = new Parser(regExp);
    
    RegularExpresionNode tree = null;
    try {
        tree = parser.Parse();
    } catch (ParserException ex) {
        JOptionPane.showMessageDialog(this,"Regular Expression has some invalid content: " + ex.getMessage(), "Invalid Regular Expression", JOptionPane.WARNING_MESSAGE);
        this.txtRegularExpression.requestFocus();
        return;
    }
    this.currentTree.generateAFNEAutomata(tree);
    this.currentTree.setCurrentRegExp(regExp);
    this.manager.setContent(currentTree.getAFNE());
    try {
        manager.convertAFNtoAFD();
    } catch (JAXBException ex) {
        Logger.getLogger(RegExpForm.class.getName()).log(Level.SEVERE, null, ex);
    } catch (Exception ex) {
        Logger.getLogger(RegExpForm.class.getName()).log(Level.SEVERE, null, ex);
    }
    JOptionPane.showMessageDialog(this, "The Regular Expression: [" +  regExp + "] has been loaded succesfully.","Succesfuly Loaded", JOptionPane.INFORMATION_MESSAGE);
}//GEN-LAST:event_btnLoadRegExpActionPerformed

private void btnEvaluateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEvaluateActionPerformed
    if(this.currentTree.getCurrentRegExp()!= null && this.currentTree.getCurrentRegExp().equals(txtRegularExpression.getText())){
        String expression = this.txtChain.getText();
        boolean isValid = false;
        try {
            isValid = manager.validateExpression(expression);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    
        if(isValid)
            JOptionPane.showMessageDialog(this, "The expression: [" + expression + "] is valid.", 
                    "Valid expression", JOptionPane.INFORMATION_MESSAGE);
        else
            JOptionPane.showMessageDialog(this, "The expression: [" + expression + "] is invalid.\nDetail: " + manager.getErrorMessage(), 
                    "Invalid expression", JOptionPane.ERROR_MESSAGE);
        this.txtChain.requestFocus();
    }else{
        JOptionPane.showMessageDialog(this, "The Current Regular Expression hasn't been loaded yet.", "Can't evaluate", JOptionPane.WARNING_MESSAGE);
        this.btnLoadRegExp.requestFocus();
    }
}//GEN-LAST:event_btnEvaluateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegExpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegExpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegExpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegExpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new RegExpForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEvaluate;
    private javax.swing.JButton btnLoadRegExp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtChain;
    private javax.swing.JTextField txtRegularExpression;
    // End of variables declaration//GEN-END:variables
}
