/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LoaderXML.java
 *
 * Created on 04-10-2014, 07:37:09 PM
 */
package BuenRecord.GUI.Loader;

import BuenRecord.Logic.AFProcessing;
import BuenRecord.RegExp.GUI.RegExpForm;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.xml.bind.JAXBException;

/**
 *
 * @author Franklin
 */
public class LoaderXML extends javax.swing.JFrame {

    
    
    public AFProcessing AFManager;
    private RegExpForm regExpForm;
    /** Creates new form LoaderXML */
    public LoaderXML() {
        initComponents();
        this.setResizable(false);
        AFManager = new AFProcessing();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtPath = new javax.swing.JTextField();
        btnPath = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnLoad = new javax.swing.JButton();
        btnValidate = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnExportAFD = new javax.swing.JButton();
        btnUnion = new javax.swing.JButton();
        btnIntersection = new javax.swing.JButton();
        lblAFLoaded = new javax.swing.JTextField();
        lblAFType = new javax.swing.JTextField();
        btnValidate1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Load XML File");

        btnPath.setText("...");
        btnPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPathActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel2.setText("AF XML Loader");

        btnLoad.setText("Load");
        btnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadActionPerformed(evt);
            }
        });

        btnValidate.setText("Expression");
        btnValidate.setEnabled(false);
        btnValidate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidateActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel3.setText("AF Loaded:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel4.setText("AF Type:");

        btnExportAFD.setText("Export AFD");
        btnExportAFD.setEnabled(false);
        btnExportAFD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportAFDActionPerformed(evt);
            }
        });

        btnUnion.setText("U");
        btnUnion.setToolTipText("Union");
        btnUnion.setEnabled(false);
        btnUnion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnionActionPerformed(evt);
            }
        });

        btnIntersection.setText("I");
        btnIntersection.setToolTipText("Intersection");
        btnIntersection.setEnabled(false);
        btnIntersection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIntersectionActionPerformed(evt);
            }
        });

        lblAFLoaded.setEditable(false);
        lblAFLoaded.setText("There isn't any AF loaded.");

        lblAFType.setEditable(false);
        lblAFType.setText("There isn't any AF loaded.");

        btnValidate1.setText("Regular Expression");
        btnValidate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidate1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAFType, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                    .addComponent(lblAFLoaded, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnExportAFD)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnUnion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnIntersection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(51, 51, 51))
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel1)
                .addContainerGap(334, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLoad, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnValidate, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnValidate1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(txtPath, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnPath, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel2)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lblAFLoaded, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(lblAFType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(6, 6, 6))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnUnion)
                            .addComponent(btnIntersection))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExportAFD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnPath)
                    .addComponent(txtPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLoad, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnValidate1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnValidate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-467)/2, (screenSize.height-328)/2, 467, 328);
    }// </editor-fold>//GEN-END:initComponents

private void btnPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPathActionPerformed
    JFileChooser saveFile = new JFileChooser();
    
    int selected = saveFile.showOpenDialog(this);
    if(selected == JFileChooser.APPROVE_OPTION)
        txtPath.setText(saveFile.getSelectedFile().getAbsolutePath());
}//GEN-LAST:event_btnPathActionPerformed

private void btnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadActionPerformed
    String tempPath = txtPath.getText();
    if(tempPath.isEmpty()){
        JOptionPane.showMessageDialog(this, "You have to select a XML File first",
                "Missing Value",JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    File tempFile = new File(tempPath);
    if(!tempFile.exists() || tempFile.isDirectory()){
        JOptionPane.showMessageDialog(this, "The current selected path is invalid.",
                "Invalid Path", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    parseXMLFile(tempFile);
        
}//GEN-LAST:event_btnLoadActionPerformed

private void btnValidateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidateActionPerformed
    String expression = JOptionPane.showInputDialog(this, "Write an expression to validate.", 
            "Input Expression", JOptionPane.INFORMATION_MESSAGE);
    
    if(expression == null || expression.isEmpty())
        return;
    
    boolean isValid = false;
        try {
            isValid = AFManager.validateExpression(expression);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    
    if(isValid)
        JOptionPane.showMessageDialog(this, "The expression: [" + expression + "] is valid.", 
                "Valid expression", JOptionPane.INFORMATION_MESSAGE);
    else
        JOptionPane.showMessageDialog(this, "The expression: [" + expression + "] is invalid.\nDetail: " + AFManager.getErrorMessage(), 
                "Invalid expression", JOptionPane.ERROR_MESSAGE);
}//GEN-LAST:event_btnValidateActionPerformed

private void btnExportAFDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportAFDActionPerformed
    JFileChooser saveFile = new JFileChooser();
    
    int selected = saveFile.showSaveDialog(this);
    if(selected == JFileChooser.APPROVE_OPTION){
        String path = saveFile.getSelectedFile().getAbsolutePath();
        try {
            AFManager.convertAFNtoAFD(path);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }    
}//GEN-LAST:event_btnExportAFDActionPerformed

private void btnUnionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnionActionPerformed
    JFileChooser saveFile = new JFileChooser();
    int selected = saveFile.showOpenDialog(this);
    if(selected == JFileChooser.APPROVE_OPTION){
        String path = saveFile.getSelectedFile().getAbsolutePath();
        
        File tempFile = new File(path);
        if(!tempFile.exists() || tempFile.isDirectory()){
            JOptionPane.showMessageDialog(this, "The current selected path is invalid.",
                    "Invalid Path", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        AFProcessing UnionAFManager = new AFProcessing();
        try {
            UnionAFManager.processXML(tempFile);
        } catch (JAXBException ex) {
            invalidAFLoaded("Error parsing xml file.");
        }
        
        String error = UnionAFManager.validateAF();
        
        if(!error.isEmpty()){
            JOptionPane.showMessageDialog(this,error, "Error At parsing XML", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        saveFile = new JFileChooser();
    
        selected = saveFile.showSaveDialog(this);
        if(selected == JFileChooser.APPROVE_OPTION){
            path = saveFile.getSelectedFile().getAbsolutePath();
            try {
                AFManager.generateUnionWithCurrentAndAFContent(UnionAFManager.getContent(), path);
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }    
    }
}//GEN-LAST:event_btnUnionActionPerformed

private void btnIntersectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIntersectionActionPerformed
    JFileChooser saveFile = new JFileChooser();
    int selected = saveFile.showOpenDialog(this);
    if(selected == JFileChooser.APPROVE_OPTION){
        String path = saveFile.getSelectedFile().getAbsolutePath();
        
        File tempFile = new File(path);
        if(!tempFile.exists() || tempFile.isDirectory()){
            JOptionPane.showMessageDialog(this, "The current selected path is invalid.",
                    "Invalid Path", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        AFProcessing IntersectionAFManager = new AFProcessing();
        try {
            IntersectionAFManager.processXML(tempFile);
        } catch (JAXBException ex) {
            invalidAFLoaded("Error parsing xml file.");
        }
        
        String error = IntersectionAFManager.validateAF();
        
        if(!error.isEmpty()){
            JOptionPane.showMessageDialog(this,error, "Error At parsing XML", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        saveFile = new JFileChooser();
    
        selected = saveFile.showSaveDialog(this);
        if(selected == JFileChooser.APPROVE_OPTION){
            path = saveFile.getSelectedFile().getAbsolutePath();
            try {
                AFManager.generateIntersectionWithCurrentAndAFContent(IntersectionAFManager.getContent(), path);
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }    
    }
}//GEN-LAST:event_btnIntersectionActionPerformed

private void btnValidate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidate1ActionPerformed
    if(this.regExpForm != null){
        this.regExpForm.dispose();
    }
    
    this.regExpForm = new RegExpForm();
    
    regExpForm.setVisible(true);
}//GEN-LAST:event_btnValidate1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoaderXML.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoaderXML.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoaderXML.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoaderXML.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new LoaderXML().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExportAFD;
    private javax.swing.JButton btnIntersection;
    private javax.swing.JButton btnLoad;
    private javax.swing.JButton btnPath;
    private javax.swing.JButton btnUnion;
    private javax.swing.JButton btnValidate;
    private javax.swing.JButton btnValidate1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField lblAFLoaded;
    private javax.swing.JTextField lblAFType;
    private javax.swing.JTextField txtPath;
    // End of variables declaration//GEN-END:variables

    private void parseXMLFile(File tempFile) {
        try {
            AFManager.processXML(tempFile);
        } catch (JAXBException ex) {
            invalidAFLoaded("Error parsing xml file.");
        }
        
        String error = AFManager.validateAF();
        
        if(!error.isEmpty()){
            invalidAFLoaded(error);
            return;
        }
        
        validAFLoaded();
    }
    
    private void validAFLoaded(){
        lblAFLoaded.setText("AF with name: [" + AFManager.getContent().getName() + "] has been loaded.");
        lblAFType.setText(this.AFManager.getContent().getAutomatonType().toString());
        btnValidate.setEnabled(true);
        btnExportAFD.setEnabled(true);
        btnIntersection.setEnabled(true);
        btnUnion.setEnabled(true);
    }
    
    private void invalidAFLoaded(String msg){
        if(!msg.isEmpty())
            JOptionPane.showMessageDialog(this,msg, 
                    "Error XML", JOptionPane.ERROR_MESSAGE);
        
        lblAFLoaded.setText("There isn't any AF loaded.");
        lblAFType.setText("There isn't any AF loaded.");
        btnValidate.setEnabled(false);
        btnExportAFD.setEnabled(false);
        btnIntersection.setEnabled(false);
        btnUnion.setEnabled(false);
    }
}
